frase = '    Curso em Vídeo Python    '
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15])
print(frase[1:15:2])
print(frase[1::2])
print(frase[::2])
print(frase.count('o'))
print(frase.count('O'))
print(frase.upper().count('O'))
print(len(frase.strip()))
print('Curso' in frase)
print(frase.find('Vídeo'))
print(frase.find('vídeo'))
print(frase.lower().find('vídeo'))
print(frase.split())
divido = frase.split()
print(divido)
print(divido[0])
print(divido[2][3])
'''frase = (frase.replace('Python', 'Android'))
print(frase)'''


