print('Olá, seja bem-vindo(a)!')
nome = input('Digite o seu nome: ')
print('É um prazer em te conhecer {}!'.format(nome))
n = input('Digite um número: ')
print('Vamos descobrir mais algumas informações sobre {}'.format(n))
print('Ele é númerico? ', n.isnumeric())
print('Ele é alpha númerico? ', n.isalnum())
print('Ele é alpha? ', n.isalpha())
print('Vamos descobrir algumas informações sobre String!')
letra = input('Digite uma para ou letra e vamos descobrir mais sobre: ')
print('A letra está apenas em minúscula ?', letra.islower())
print('A letra está apenas em maiúscula? ', letra.isupper())
print('Essa palavra contém espaços ?', letra.isspace())
