nome = str(input('Digite seu nome completo: ')).strip()
nome_fatiado = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é: {}'.format(nome_fatiado[0]))
print('Seu último nome é: {}'.format(nome_fatiado[len(nome_fatiado)-1]))
